### ISSUE TITLE
TypeError when importing bayesian_optimization

### ISSUE THREAD

**Issue by meetshah1995** [automl/RoBO#51]
I am getting this error after installing the master branch.

```
>>> from robo.fmin import bayesian_optimization
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/RoBO-0.2.0-py2.7.egg/robo/fmin/__init__.py", line 1, in <module>
    from .bayesian_optimization import bayesian_optimization
  File "/usr/local/lib/python2.7/dist-packages/RoBO-0.2.0-py2.7.egg/robo/fmin/bayesian_optimization.py", line 6, in <module>
    from robo.models.gaussian_process import GaussianProcess
  File "/usr/local/lib/python2.7/dist-packages/RoBO-0.2.0-py2.7.egg/robo/models/gaussian_process.py", line 14, in <module>
    class GaussianProcess(BaseModel):
  File "/usr/local/lib/python2.7/dist-packages/RoBO-0.2.0-py2.7.egg/robo/models/gaussian_process.py", line 71, in GaussianProcess
    def train(self, X, y, do_optimize=True):
TypeError: unbound method _check_shapes_train() must be called with BaseModel instance as first argument (got function instance instead)

```

**Comment by aaronkl** [comment]
Which python version do you use? Please make sure that you use python 3 as RoBO does not support python2 anymore

**Comment by aaronkl** [comment]
I guess this is fixed now
