### ISSUE TITLE
fmin code doesn't work

### ISSUE THREAD

**Issue by qqTYXn7** [automl/RoBO#72]
The code in the tutorial for black box function optimization doesn't work ( https://automl.github.io/RoBO/tutorials.html#blackbox-function-optimization-with-robo ).
Additionally test_fmin/test_fmin_interface.py throws the same errors:

`test_fmin $ python test_fmin_interface.py Traceback (most recent call last):
  File "test_fmin_interface.py", line 4, in <module>
    from robo.fmin import random_search, bayesian_optimization, bohamiann
  File "/usr/local/lib/python2.7/dist-packages/RoBO-0.2.1-py2.7.egg/robo/fmin/__init__.py", line 2, in <module>
    from .bayesian_optimization import bayesian_optimization
  File "/usr/local/lib/python2.7/dist-packages/RoBO-0.2.1-py2.7.egg/robo/fmin/bayesian_optimization.py", line 6, in <module>
    from robo.models.gaussian_process import GaussianProcess
  File "/usr/local/lib/python2.7/dist-packages/RoBO-0.2.1-py2.7.egg/robo/models/gaussian_process.py", line 14, in <module>
    class GaussianProcess(BaseModel):
  File "/usr/local/lib/python2.7/dist-packages/RoBO-0.2.1-py2.7.egg/robo/models/gaussian_process.py", line 70, in GaussianProcess
    def train(self, X, y, do_optimize=True):
TypeError: unbound method _check_shapes_train() must be called with BaseModel instance as first argument (got function instance instead)`

**Comment by aaronkl** [comment]
The problem is that you use python2.7. RoBO only supports python3.4 and python3.5. See also here https://github.com/automl/RoBO/issues/62
