### ISSUE TITLE
example f_min.py DIRECT error

### ISSUE THREAD

**Issue by Schraivogel** [automl/RoBO#75]
Hi,
seems like i have a similar problem with the DIRECT library. Running RoBO on a virtual x64 ubuntu machine using python3.4 within a venv. Any ideas what I can do? example_blr.py runs...
... 
INFO:robo.solver.bayesian_optimization:Maximize acquisition function...
Call-back cb_fcn_in_direct__user__routines failed.
Traceback (most recent call last):
  File "example_fmin.py", line 22, in <module>
    results = bayesian_optimization(objective_function, lower, upper, num_iterations=50)
  File "/home/student/Documents/venv/RoBo/lib/python3.4/site-packages/RoBO-0.2.1-py3.4.egg/robo/fmin/bayesian_optimization.py", line 133, in bayesian_optimization
  File "/home/student/Documents/venv/RoBo/lib/python3.4/site-packages/RoBO-0.2.1-py3.4.egg/robo/solver/bayesian_optimization.py", line 167, in run
  File "/home/student/Documents/venv/RoBo/lib/python3.4/site-packages/RoBO-0.2.1-py3.4.egg/robo/solver/bayesian_optimization.py", line 245, in choose_next
  File "/home/student/Documents/venv/RoBo/lib/python3.4/site-packages/RoBO-0.2.1-py3.4.egg/robo/maximizers/direct.py", line 69, in maximize
  File "/home/student/Documents/venv/RoBo/lib/python3.4/site-packages/DIRECT/__init__.py", line 202, in solve
    cdata
ValueError: data type must provide an itemsize

Thanks,
Stephan

**Comment by aaronkl** [comment]
Hi, the problem is that by default we suppress DIRECTs output to unclutter RoBOs console output. It seems that this leads to problems on some OS systems. I changed RoBOs default verbosity level such that it prints DIRECTs output. Could you pull the master branch and try it again?

**Comment by Schraivogel** [comment]
Hi,
thanks for the tip. It didn't resolve the error though... Must be an issue on my machine.
