### ISSUE TITLE
__init__() got an unexpected keyword argument 'dim'

### ISSUE THREAD

**Issue by wa1618i** [automl/RoBO#78]
I tried the example on the page: https://github.com/automl/RoBO/blob/master/examples/example_fabolas.py
But then it generates error: 
Traceback (most recent call last):

  File "<ipython-input-7-5297c9852340>", line 12, in <module>
    s_min=s_min, s_max=s_max, num_iterations=100)

  File "/home/lemma/miniconda2/envs/py36/lib/python3.6/site-packages/RoBO-0.2.1-py3.6.egg/robo/fmin/fabolas.py", line 106, in fabolas
    ndim=n_dims+1, dim=d)

TypeError: __init__() got an unexpected keyword argument 'dim'

Not sure what's going on here?

**Comment by wa1618i** [comment]
Here trying the example: https://github.com/automl/RoBO/blob/master/examples/example_bohamiann.py
Also gives an error:
INFO:root:Iter    12900 : NLL =  2.5185e+03 MSE = 7.7797e-02 Samples= 100 Time = 119.19
INFO:robo.solver.bayesian_optimization:Time to train the model: 119.193871
INFO:robo.solver.bayesian_optimization:Maximize acquisition function...
Traceback (most recent call last):

  File "<ipython-input-1-fe8eaf63a113>", line 21, in <module>
    results = bohamiann(objective_function, lower, upper, num_iterations=20)

  File "/home/lemma/miniconda2/envs/py36/lib/python3.6/site-packages/RoBO-0.2.1-py3.6.egg/robo/fmin/bohamiann.py", line 85, in bohamiann
    x_best, f_min = bo.run(num_iterations)

  File "/home/lemma/miniconda2/envs/py36/lib/python3.6/site-packages/RoBO-0.2.1-py3.6.egg/robo/solver/bayesian_optimization.py", line 167, in run
    new_x = self.choose_next(self.X, self.y, do_optimize)

  File "/home/lemma/miniconda2/envs/py36/lib/python3.6/site-packages/RoBO-0.2.1-py3.6.egg/robo/solver/bayesian_optimization.py", line 245, in choose_next
    x = self.maximize_func.maximize()

  File "/home/lemma/miniconda2/envs/py36/lib/python3.6/site-packages/RoBO-0.2.1-py3.6.egg/robo/maximizers/direct.py", line 58, in maximize
    maxf=self.n_func_evals)

  File "/home/lemma/miniconda2/envs/py36/lib/python3.6/site-packages/DIRECT/__init__.py", line 202, in solve
    cdata

ValueError: data type must provide an itemsize

**Comment by aaronkl** [comment]
How did you install george? Did you make sure that you installed our fork of [george](https://github.com/automl/george) 

About the second problem, see #77

**Comment by wa1618i** [comment]
Installing your fork solved the issue THX
