### ISSUE TITLE
example fmin not working

### ISSUE THREAD

**Issue by rizplate** [automl/RoBO#92]
I am on Mac, pip, python3

```python example_fmin.py
INFO:robo.solver.bayesian_optimization:Start iteration 3 ...
INFO:robo.solver.bayesian_optimization:Train model...
ERROR:robo.solver.bayesian_optimization:Model could not be trained!
Traceback (most recent call last):
  File "example_fmin.py", line 22, in <module>
    results = bayesian_optimization(objective_function, lower, upper, num_iterations=50)
  File "/dir//python3.6/site-packages/robo/fmin/bayesian_optimization.py", line 137, in bayesian_optimization
    x_best, f_min = bo.run(num_iterations)
  File "/dir//python3.6/site-packages/robo/solver/bayesian_optimization.py", line 167, in run
    new_x = self.choose_next(self.X, self.y, do_optimize)
  File "/dir//python3.6/site-packages/robo/solver/bayesian_optimization.py", line 236, in choose_next
    self.model.train(X, y, do_optimize=do_optimize)
  File "/dir//python3.6/site-packages/robo/models/base_model.py", line 71, in func_wrapper
    return func(self, X, y, *args, **kwargs)
  File "/dir//python3.6/site-packages/robo/models/gaussian_process_mcmc.py", line 115, in train
    len(self.kernel.pars) + 1,
  File "/dir//python3.6/site-packages/george/kernels.py", line 66, in __getattr__
    raise AttributeError(name)
AttributeError: pars
```

**Comment by kejiashi** [comment]
this is solved in #93

**Comment by akamaus** [comment]
Just to clarify a bit. george-0.3.1 from pip wouldn't work, a **forked** version must be installed
