### ISSUE TITLE
Fabola example is broken

### ISSUE THREAD

**Issue by cfusting** [automl/RoBO#95]
Traceback (most recent call last):
  File "example_fabolas.py", line 125, in <module>
    s_min=s_min, s_max=s_max, num_iterations=100)
  File "/home/chris/anaconda3/lib/python3.6/site-packages/RoBO-0.2.2-py3.6.egg/robo/fmin/fabolas.py", line 201, in fabolas
IndexError: list index out of range
 
I'll have a look.

**Comment by cfusting** [comment]
The hack to fix this is to set n_init = len(subsets).
